POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "rafli",
    "email": "admin@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
//get All users
GET http://localhost:5000/users

###
//GET single users
GET http://localhost:5000/users/043c2e27-9764-4bf1-93a3-b1406a27bfff


###
DELETE http://localhost:5000/users/043c2e27-9764-4bf1-93a3-b1406a27bfff

###
//login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/products

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 4",
    "price": 12000
}